"""Synthetic starter workspace used by ``evidence init``."""

from __future__ import annotations

import json
from pathlib import Path


def initialize_workspace(destination: Path) -> list[Path]:
    destination.mkdir(parents=True, exist_ok=False)
    documents = {
        "task-profile.json": {
            "schema_name": "TaskProfileV1",
            "schema_version": "1.0.0",
            "record_id": "task-profile-synthetic-v1",
            "task_id": "synthetic-rally-boundaries",
            "sport": "badminton",
            "prediction_unit": "rally_boundary",
            "boundary_tolerance_frames": 15,
            "scorer": {"name": "khelsutra-rally-boundary", "version": "1.0.0"},
            "sample_ids": ["synthetic-match-001"],
            "notes": "Synthetic contract fixture; not product evidence.",
        },
        "scenario-profile.json": {
            "schema_name": "ScenarioProfileV1",
            "schema_version": "1.0.0",
            "record_id": "scenario-synthetic-match-001",
            "sample_id": "synthetic-match-001",
            "visible_courts": 3,
            "simultaneously_active_games": 2,
            "target_court_id": "court-a",
            "camera": {"motion": "fixed", "angle": "corner", "placement": "synthetic-tripod"},
            "capture": {
                "width": 1920,
                "height": 1080,
                "fps": 30,
                "cuts": 0,
                "audio_available": True,
                "lighting": "even",
                "occlusion": "partial",
            },
            "source_duration_seconds": 600,
            "adult_rights_cleared": True,
            "notes": "Synthetic contract fixture; no media exists.",
        },
    }
    written: list[Path] = []
    for name, document in documents.items():
        path = destination / name
        path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        written.append(path)
    readme = destination / "README.md"
    readme.write_text(
        "# Synthetic evidence workspace\n\nGenerated by `evidence init`; not product evidence.\n",
        encoding="utf-8",
    )
    written.append(readme)
    return written
