"""Render the evidence site's data-bearing sections from the registries.

The site's prose is authored; its release index is not. Everything between the generated markers
in `site/index.html` is a deterministic allowlisted projection of `registry/*.json`, so a page that
says "no official releases" says it because the registry is empty, not because someone typed it.

    python tools/render_site.py

`tests/test_site.py` fails if the checked-in page differs from what this renders.
"""

from __future__ import annotations

import hashlib
import html
import json
from pathlib import Path
from typing import Any

from khelsutra_evidence.validation import safety_issues, validate_document

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry"
PAGE = ROOT / "site" / "index.html"

BEGIN = "      <!-- BEGIN GENERATED release index -->"
END = "      <!-- END GENERATED release index -->"

# The only fields a release reference may put on a public page. A registry entry carrying anything
# else is refused rather than rendered without it, because a field nobody allowlisted is a field
# nobody reviewed.
ALLOWED_RELEASE_FIELDS = ("artifact_id", "digest", "media_type", "size_bytes")
ALLOWED_DIGEST_FIELDS = ("algorithm", "value")

REGISTRY_TITLES = {
    "official": "Official releases",
    "community": "Community releases",
}
REGISTRY_NOTES = {
    "official": "Published and signed off through the KhelSutra evidence programme.",
    "community": "Self-run evidence that passed contract and safety review. Not KhelSutra "
    "verification, endorsement, licence clearance, or a quality award.",
}

JsonObject = dict[str, Any]


class SiteRefused(ValueError):
    """The registries carry something the site may not render."""


def load_registry(name: str) -> JsonObject:
    document: JsonObject = json.loads((REGISTRY / f"{name}.json").read_text(encoding="utf-8"))
    issues = validate_document(document)
    if issues:
        raise SiteRefused(
            f"registry/{name}.json is not a valid registry: "
            + "; ".join(issue.render() for issue in issues)
        )
    if document["registry"] != name:
        raise SiteRefused(f"registry/{name}.json declares registry {document['registry']!r}")
    return document


def project_release(release: JsonObject, where: str) -> JsonObject:
    unknown = sorted(set(release) - set(ALLOWED_RELEASE_FIELDS))
    if unknown:
        raise SiteRefused(f"{where} carries unpublishable field(s): {', '.join(unknown)}")
    digest = release["digest"]
    unknown_digest = sorted(set(digest) - set(ALLOWED_DIGEST_FIELDS))
    if unknown_digest:
        raise SiteRefused(
            f"{where}.digest carries unpublishable field(s): {', '.join(unknown_digest)}"
        )
    projected: JsonObject = {
        "artifact_id": release["artifact_id"],
        "digest": {key: digest[key] for key in ALLOWED_DIGEST_FIELDS},
    }
    for field in ("media_type", "size_bytes"):
        if field in release:
            projected[field] = release[field]
    issues = safety_issues(projected, where)
    if issues:
        raise SiteRefused(
            f"{where} is not publishable: " + "; ".join(issue.render() for issue in issues)
        )
    return projected


def project_registries() -> dict[str, list[JsonObject]]:
    projected: dict[str, list[JsonObject]] = {}
    for name in ("official", "community"):
        document = load_registry(name)
        entries = [
            project_release(release, f"registry.{name}.releases[{index}]")
            for index, release in enumerate(document["releases"])
        ]
        projected[name] = sorted(entries, key=lambda entry: str(entry["artifact_id"]))
    return projected


def release_data_digest(projected: dict[str, list[JsonObject]]) -> str:
    encoded = json.dumps(
        projected, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode()
    return hashlib.sha256(encoded).hexdigest()


def _rows(entries: list[JsonObject]) -> list[str]:
    lines = [
        "          <table>",
        "            <thead><tr><th>Release</th><th>SHA-256</th><th>Type</th></tr></thead>",
        "            <tbody>",
    ]
    for entry in entries:
        media_type = html.escape(str(entry.get("media_type", "—")))
        lines.append(
            "              <tr>"
            f"<td>{html.escape(str(entry['artifact_id']))}</td>"
            f"<td><code>{html.escape(str(entry['digest']['value']))}</code></td>"
            f"<td>{media_type}</td>"
            "</tr>"
        )
    lines += ["            </tbody>", "          </table>"]
    return lines


def render_block(projected: dict[str, list[JsonObject]]) -> str:
    total = sum(len(entries) for entries in projected.values())
    lines = [
        BEGIN,
        "      <!-- Generated by tools/render_site.py from registry/*.json. Do not hand-edit. -->",
        '      <section aria-labelledby="release-index">',
        '        <h2 id="release-index">Release index</h2>',
    ]
    if total == 0:
        lines.append(
            '        <p class="notice">Both registries are empty, so no release is published '
            "here yet. This sentence is rendered from the registry data, not asserted alongside "
            "it.</p>"
        )
    for name in ("official", "community"):
        entries = projected[name]
        lines += [
            f'        <div class="registry" data-registry="{name}">',
            f"          <h3>{html.escape(REGISTRY_TITLES[name])}</h3>",
            f"          <p>{html.escape(REGISTRY_NOTES[name])}</p>",
        ]
        if entries:
            lines += _rows(entries)
        else:
            lines.append(f'          <p class="empty">No {name} releases.</p>')
        lines.append("        </div>")
    lines += [
        '        <p class="provenance">Release data digest '
        f"<code>{release_data_digest(projected)}</code> — the SHA-256 of the canonical projection "
        "of the registry entries above.</p>",
        "      </section>",
        END,
    ]
    return "\n".join(lines)


def render_page() -> str:
    page = PAGE.read_text(encoding="utf-8")
    start = page.index(BEGIN)
    end = page.index(END) + len(END)
    return page[:start] + render_block(project_registries()) + page[end:]


def main() -> int:
    rendered = render_page()
    PAGE.write_text(rendered, encoding="utf-8")
    projected = project_registries()
    print(
        f"{PAGE.relative_to(ROOT)}: "
        f"{sum(len(v) for v in projected.values())} release(s); "
        f"digest {release_data_digest(projected)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
